runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /styles
  static_dir: styles


- url: .*
  script: routes.app






libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
